### ISSUE TITLE
Links to supplemental documents on code.google.com for Darwin Core RDF Guide are broken.

### ISSUE THREAD

**Issue by chicoreus** [tdwg/rs.tdwg.org#14]
The Darwin Core RDF Guide (http://rs.tdwg.org/dwc/terms/guides/rdf/index.htm) contains two references that point to resources on code.google.com, both of which now redirect to code.google.com/archive/... and return an error "There was an error obtaining wiki data:"

[DWC-RDF-ANCILLARY] | https://code.google.com/p/tdwg-rdf/wiki/DwCAncillary | Ancillary documents related to the Darwin Core RDF Guide

and 

[RDF-BEGINNERS-GUIDE] | http://code.google.com/p/tdwg-rdf/wiki/Beginners | Beginner's Guide to RDF. Biodiversity informatics using RDF and OWL.

**Comment by baskaufs** [comment]
These links have been fixed in the revised document which will (hopefully) go live soon along with the rest of the DwC website.
