### ISSUE TITLE
documents metadata header in script-generated standards landing pages aren't styled

### ISSUE THREAD

**Issue by baskaufs** [tdwg/rs.tdwg.org#27]
I made no attempt to style the Documents metadata.  You can see what I did in lines 142-158 of [the build script](https://github.com/tdwg/rs.tdwg.org/blob/stds-pages/html/stds-pages/build.py).  I'm sure you have preferences on how the styling should be done to be consistent with the website theme.

**Comment by peterdesmet** [comment]
Ok, would need to look into this. Some margin/padding is indeed off (http://rs.tdwg.org/dwc.htm):

<img width="994" alt="Screenshot 2020-09-09 at 21 26 47" src="https://user-images.githubusercontent.com/600993/92644175-39d54e80-f2e3-11ea-98e4-074e7c06b131.png">

**Comment by peterdesmet** [comment]
Correct link to Steve's ref to the build script:
https://github.com/tdwg/rs.tdwg.org/blob/493f08097d6750d9aa19ed7bcc6e4a8a0a10d219/html/stds-pages/build.py#L142-L158

**Comment by peterdesmet** [comment]
@baskaufs it seems that script is creating md files. Where I these translated to html files? I.e. where is the navbar and footer added?

**Comment by baskaufs** [comment]
@peterdesmet The markdown files are ending up in subdirectories of the docs directory, just as is the case with the [list of terms doc](https://dwc.tdwg.org/list/). So they are being rendered by Jeckyll and I guess the navbar/footer are being added by the page template.

That is, [https://github.com/tdwg/dwc/blob/master/docs/list/index.md](https://github.com/tdwg/dwc/blob/master/docs/list/index.md) is rendered to [this page](https://dwc.tdwg.org/list/), and the three new pages are in analogous subdirectories of docs, so when the branch is merged into master, they styling should just happen.

**Comment by peterdesmet** [comment]
Hmm, seems that markdown pages are generated in `html/stds-pages/output`, but I don't see the equivalent of a [`_config.yml`](https://github.com/tdwg/dwc/blob/master/docs/_config.yml) that Darwin Core has. @MattBlissett is this something that is defined at server level? rs.tdwg.org is not hosted from GitHub pages it seems.

**Comment by baskaufs** [comment]
@peterdesmet Sorry, my answer makes no sense, I didn't look at the issue URL and though you were talking about the list of terms documents. Please disregard.

**Comment by baskaufs** [comment]
I think this issue is moot. It conflates several different problems. The proximate one (styling for the standards landing pages) is handled by the styling of the TDWG website once the script-generated Markdown pages are moved into the `website` repo and rendered to HTML by Jekyll.
