### ISSUE TITLE
Deploy rs.tdwg.org redirection services

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/rs.tdwg.org#36]
- [x] Deploy services
- [x] Close relevant issues in all TDWG GH repositories

**Comment by MattBlissett** [comment]
It's now deployed to http://rs.tdwg.org with this release: https://github.com/tdwg/rs.tdwg.org/releases/tag/20200304

**Comment by MattBlissett** [comment]
* Example RDF: http://rs.tdwg.org/dwc/dwctype/MachineObservation.rdf
* Example HTML: http://rs.tdwg.org/dwc/dwctype/MachineObservation.htm
* Example content negotiation
  * HTML if you click in a browser: http://rs.tdwg.org/dwc/dwctype/MachineObservation
  * Turtle: `curl -SsiL -H 'Accept: text/turtle' http://rs.tdwg.org/dwc/dwctype/MachineObservation`
* Link to a document: http://rs.tdwg.org/sds/doc/specification/2017-04-25

More examples are on the readme, which http://rs.tdwg.org redirects to.

**Comment by baskaufs** [comment]
I've gone through the issues in rs.tdwg.org and closed several. Many of them are long-term issues that either need significant work or need to have some consensus or decision. I also looked through several of the issues trackers in several of the other likely repos and didn't find anything else related to this that needed to be closed. So I think we are done here.
