### ISSUE TITLE
DwC term list document does not display all attributes

### ISSUE THREAD

**Issue by tucotuco** [tdwg/rs.tdwg.org#66]
Perhaps related to https://github.com/tdwg/rs.tdwg.org/issues/65, if not in cause, at least in nature.

Details of terms in the HTML rendering of the Darwin Core term list document do not show the ABCD mapping (tdwgutility:abcdEquivalence) while the turtle document does.

Example:
https://dwc.tdwg.org/list/#dwc_georeferenceSources
http://rs.tdwg.org/dwc/terms/version/georeferenceSources-2020-10-28.ttl

**Comment by baskaufs** [comment]
The list of terms document started as a generic script that included the standard properties but not all of the idiosyncratic DwC properties. But it is customizable. We just need to add some more blocks of code like [this](https://github.com/tdwg/dwc/blob/master/build/build-termlist.py#L316) and add the relevant column headers to the list [here](https://github.com/tdwg/dwc/blob/master/build/build-termlist.py#L95). 

In contrast, the Turtle document includes all of the metadata that exists. Make a note of what's missing in this issue and I will fix the script to make it show up.

**Comment by baskaufs** [comment]
Resolved in https://github.com/tdwg/dwc/pull/317
